spring:
  application:
    name: dine-in-order-api

  datasource:
    url: jdbc:mysql://localhost:3306/dine-in-order?createDatabaseIfNotExist=true
    username: root
    password: Sumit@7978
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

